name: barcode_reader_app
description: A highly scalable Flutter application for barcode scanning with advanced features.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

  # State Management
  provider: ^6.0.5 # Updated version (changed from ^6.1.5)
  riverpod: ^2.5.0 # Updated version

  # Networking & API
  http: ^1.3.0 # Updated versionion
  dio: ^5.4.0 # Updated version

  # Barcode Scanning & QR Code
  flutter_barcode_scanner: ^2.0.0 # Updated version (changed from ^2.1.0)
  qr_flutter: ^4.1.0 # Updated version (changed from ^4.2.0)

  # Database & Local Storage
  hive: ^2.2.3 # Updated version (changed from ^2.3.0)
  hive_flutter: ^1.1.0 # Updated version
  shared_preferences: ^2.3.0 # Updated version

  # Firebase (if needed)
  firebase_core: ^2.19.0 # Updated version
  firebase_auth: ^4.9.0 # Updated version
  cloud_firestore: ^4.13.0 # Updated version

  # UI & Design
  google_fonts: ^6.2.0 # Updated version
  font_awesome_flutter: ^10.7.0 # Updated version
  lottie: ^2.7.0 # Updated version

  # State & Utility Libraries
  freezed_annotation: ^2.2.0 # Updated version (changed from ^2.5.0)
  json_serializable: ^6.8.0 # Updated version
  logger: ^2.1.0 # Updated version

  # Navigation & Routing
  go_router: ^13.2.0 # Updated version
  auto_route: ^7.1.0 # Updated version

  # Security & Encryption
  encrypt: ^5.0.1 # Updated to a valid version
  flutter_secure_storage: ^9.1.0 # Updated version

  # Background Services & Push Notifications
  flutter_local_notifications: ^15.1.0 # Updated version
  workmanager: any # or a specific version like: workmanager: 1.0.0
  firebase_messaging: ^14.8.0 # Updated version

  # File Handling & Permissions
  permission_handler: ^11.1.0 # Updated version
  path_provider: ^2.0.15 # Updated to a valid version
  image_picker: ^1.1.0 # Updated version

  # Animations & Effects
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0 # Updated to a valid version

  # Testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.5.2
  hive_generator: ^2.0.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/CustomFont-Regular.ttf

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700
