name: barcode_reader_app
description: A highly scalable Flutter application for barcode scanning with advanced features.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2       # updated from ^0.18.0

  # State Management
  provider: ^6.1.0  # Consider updating to a higher version if compatible
  riverpod: ^2.5.0  # ...review flutter pub outdated for more details...

  # Networking & API
  http: ^1.3.0 # Updated version
  dio: ^5.4.0 # Updated version

  # Barcode Scanning & QR Code
  flutter_barcode_scanner: ^2.0.0 # Updated version (changed from ^2.1.0)
  qr_flutter: ^4.1.0 # Updated version (changed from ^4.2.0)

  # Database & Local Storage
  hive: ^2.2.3 # Updated version (changed from ^2.3.0)
  hive_flutter: ^1.1.0 # Updated version
  shared_preferences: ^2.3.0 # Updated version

  # Firebase (if needed)
  firebase_core: ^3.12.1     # updated from ^2.19.0
  firebase_auth: ^5.5.1      # updated from ^4.9.0
  cloud_firestore: ^5.6.5    # updated from ^4.13.0

  # UI & Design
  google_fonts: ^6.2.0 # Updated version
  font_awesome_flutter: ^10.7.0 # Updated version
  lottie: ^3.3.1           # updated from ^2.7.0

  # State & Utility Libraries
  freezed_annotation: ^3.0.0     # updated from ^2.2.0
  json_serializable: ^6.9.0      # updated from ^6.8.0
  logger: ^2.1.0 # Updated version

  # Navigation & Routing
  go_router: ^14.8.1      # updated from ^13.2.0
  auto_route: ^9.3.0+1     # updated from ^7.1.0

  # Security & Encryption
  encrypt: ^5.0.1 # Updated to a valid version
  flutter_secure_storage: ^10.0.0-beta.4 # Updated version

  # Background Services & Push Notifications
  flutter_local_notifications: ^19.0.0  # updated from ^15.1.0
  workmanager: any # or a specific version like: workmanager: 1.0.0
  firebase_messaging: ^15.2.4  # updated from ^14.8.0

  # File Handling & Permissions
  permission_handler: ^11.4.0  # updated from ^11.1.0
  path_provider: ^2.1.5       # updated from ^2.0.15 (resolvable version 2.1.5)
  image_picker: ^1.1.0 # Updated version

  # Animations & Effects
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0 # Updated to a valid version

  # Testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0            # updated from ^3.0.1
  build_runner: ^2.4.15            # updated from ^2.4.8
  freezed: ^3.0.0-0.0.dev  # downgraded to resolve source_gen incompatibility with hive_generator
  hive_generator: ^2.0.0
  auto_route_generator: ^9.0.0     # updated from ^7.3.2

flutter:
  uses-material-design: true

  # Removed local asset entries since no assets are available.
  # To load assets from an online source at runtime, use network image providers.
  # assets:
  #   - assets/images/
  #   - assets/fonts/CustomFont-Regular.ttf
  #   - assets/fonts/CustomFont-Bold.ttf

  # Optionally, you can also remove the fonts section if you plan to use online fonts.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

# Your dependencies are set to the newest resolvable versions.
# If you need to use the 'Latest' versions, update constraints manually and test for compatibility.
